spring:
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  cliente:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
